# -*- coding: utf-8 -*-
"""ASL Alphabet using SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1quGiet_NTleHEv4kIKuoBf3Klk2MFNyR
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("grassknoted/asl-alphabet")

print("Path to dataset files:", path)

!pip install opencv-python-headless
import os
import cv2
data=[]
labels=[]
base_download_path = os.path.join(path, 'asl_alphabet_train', 'asl_alphabet_train')

print(f"Number of samples in data: {len(data)}")
print(f"Number of labels: {len(labels)}")

for label in os.listdir(base_download_path):
    label_path = os.path.join(base_download_path, label)
    if not os.path.isdir(label_path):
        continue
    for image_name in os.listdir(label_path):
        image_path = os.path.join(label_path, image_name)
        img=cv2.imread(image_path)
        if img is None:
          print(f"Warning: Could not load image {image_path}. Skipping.")
          continue
        img= cv2.resize(img,(64,64))
        gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
        data.append(gray.flatten())
        labels.append(label)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data,labels, test_size=0.2, random_state=42)

from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
svm_linear= SVC(kernel='linear')
svm_linear.fit(data,labels)
y_pred=svm_linear.predict(x_test)
accuracy_score(y_test,y_pred)